# Generated by Django 4.1 on 2022-08-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0002_rename_bookchapter_chapter_rename_partline_line_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='part',
            new_name='section',
        ),
    ]
